plugins:
  - prettier-plugin-astro

overrides:
  - files: '*.astro'
    options:
      parser: astro

proseWrap: always
singleQuote: true
semi: true
tabWidth: 2
useTabs: false
printWidth: 80
trailingComma: es5
